context:
  version: "0.2.0"

package:
  name: gamma-lake
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gamma-lake/gamma_lake-${{ version }}.tar.gz
  sha256: 072f9af31cdd05feed599ded7a45edb90c975a82930298581db1268e08b356d8

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - ccflow >=0.8
    - deltalake
    - packaging
    - polars >=1.33.1
    - polars-io-tools >=0.2.1,<0.3
    - pyarrow >=10
    - pydantic >=2
    - typing-extensions >=4.4.0

tests:
  - python:
      imports:
        - gammalake
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/Point72/gamma-lake
  summary: High-performance feature store built on Delta Lake and Ray
  description: |
    Gamma Lake is a feature store built on Delta Lake and Ray, designed for
    efficient storage, versioning, and retrieval of time-indexed features
    backed by Polars DataFrames.
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/Point72/gamma-lake
  documentation: https://github.com/Point72/gamma-lake/wiki

extra:
  recipe-maintainers:
    - timkpaine
